[book]
src = "src"
authors = ["0x9ef"]
title = "The Monolith Programming Language"
description = "The Monolith Programming Language Book"
multilingual = false

[output.html.playpen]
editable = true
copyable = true

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/monolithlang/monolith"